opt typescript = true
opt server_output = "./network/server.luau"
opt client_output = "../client/network/client.luau"
opt types_output = "../shared/networktypes.luau"

opt call_default = "ManyAsync"
opt casing = "camelCase"

opt include_profile_labels = true
--opt async_lib = "require(game:GetService('ReplicatedStorage').rbxts_include.RuntimeLib)"

-- !!! zap src/server/network.zap

-- ====================================================================================
-- TYPES

--[[
    Player in-game data and data of shark slots
]]
type SharkSlot = struct { 
    shark: u8,

    alive: boolean,
    created: boolean,

    hp: u8(0..100),
    maxhp: u8(0..100),

    hunger: u8(0..100),
    maxhunger: u8(0..100),

    exp: u8(0..100),
    maxexp: u8(0..100),

    upgrade: u8(0..2),
    level: u8,
    -- title size damage speed are from shared
}

--[[
    UserData type is generated by Zap within definition files
]]
type UserData = struct {
    -- sharkcoins
    coins: u32(..100000), --100,000; 4,294,967,295
    sharkcoins: u16, --65,535
    revivetokens: u8,

    ownedsharks: u8[],

    -- zap uses luau-based indexing so 0..3 is 3 elements
    slots: SharkSlot[3],
}

-- ====================================================================================
-- EVENTS

event PlayerDataEvent = {
    from: Server,
    type: Reliable,
    data: UserData
}

-- Minimizing
event IngameDataEvent = {
    from: Server,
    type: Reliable,
    data: SharkSlot
}

-- SpawnController & SpawnService
-- Spawns the player (player always has the hitbox)
event SpawnSlot = {
    from: Client,
    type: Reliable,
    data: u8(1..3), --slot number
}

event SpawnResult = {
    from: Server,
    type: Reliable,
    data: (enum { Success, Fail }) --success marks creation of hitbox
}
