// Server generated by Zap v0.6.29 (https://github.com/red-blox/zap)
export declare const sendEvents: () => void
export type UserData = {
	["coins"]: number,
};

export declare const PlayerData: {
	fire: (player: Player, value: {
		["coins"]: number,
	}) => void;
	fireAll: (value: {
		["coins"]: number,
	}) => void;
	fireExcept: (except: Player, value: {
		["coins"]: number,
	}) => void;
	fireList: (list: Player[] | Record<string | number | symbol, Player> | Map<unknown, Player>, value: {
		["coins"]: number,
	}) => void;
	fireSet: (set: Set<Player> | Map<Player, unknown>, value: {
		["coins"]: number,
	}) => void
};
