// Client generated by Zap v0.6.29 (https://github.com/red-blox/zap)
export declare const sendEvents: () => void
export type UserData = {
	["coins"]: number,
};

export declare const PlayerData: {
	on: (callback: (value: {
		["coins"]: number,
	}) => void) => () => void;
};
