// Client generated by Zap v0.6.29 (https://github.com/red-blox/zap)
export declare const sendEvents: () => void
export type PartialSharkSlot = {
	["shark"]?: number | undefined,
	["dead"]?: boolean | undefined,
	["hunger"]?: number | undefined,
	["exp"]?: number | undefined,
	["upgrade"]?: number | undefined,
	["level"]?: number | undefined,
};
export type UserData = {
	["coins"]: number,
	["gems"]: number,
	["revivetokens"]: number,
	["slots"]: [{
		["shark"]: number,
		["dead"]: boolean,
		["hunger"]: number,
		["exp"]: number,
		["upgrade"]: number,
		["level"]: number,
	}, {
		["shark"]: number,
		["dead"]: boolean,
		["hunger"]: number,
		["exp"]: number,
		["upgrade"]: number,
		["level"]: number,
	}, {
		["shark"]: number,
		["dead"]: boolean,
		["hunger"]: number,
		["exp"]: number,
		["upgrade"]: number,
		["level"]: number,
	}],
};
export type SharkSlot = {
	["shark"]: number,
	["dead"]: boolean,
	["hunger"]: number,
	["exp"]: number,
	["upgrade"]: number,
	["level"]: number,
};

export declare const SpawnEvent: {
	fire: (value: number) => void;
};
export declare const SlotDeltaEvent: {
	on: (callback: (value: {
		["shark"]?: number | undefined,
		["dead"]?: boolean | undefined,
		["hunger"]?: number | undefined,
		["exp"]?: number | undefined,
		["upgrade"]?: number | undefined,
		["level"]?: number | undefined,
	}) => void) => () => void;
};
export declare const PlayerDataEvent: {
	on: (callback: (value: {
		["coins"]: number,
		["gems"]: number,
		["revivetokens"]: number,
		["slots"]: [{
			["shark"]: number,
			["dead"]: boolean,
			["hunger"]: number,
			["exp"]: number,
			["upgrade"]: number,
			["level"]: number,
		}, {
			["shark"]: number,
			["dead"]: boolean,
			["hunger"]: number,
			["exp"]: number,
			["upgrade"]: number,
			["level"]: number,
		}, {
			["shark"]: number,
			["dead"]: boolean,
			["hunger"]: number,
			["exp"]: number,
			["upgrade"]: number,
			["level"]: number,
		}],
	}) => void) => () => void;
};
