// Client generated by Zap v0.6.29 (https://github.com/red-blox/zap)
export declare const sendEvents: () => void
export type SharkSlot = {
	["shark"]: number,
	["dead"]: boolean,
	["hp"]: number,
	["maxhp"]: number,
	["hunger"]: number,
	["maxhunger"]: number,
	["exp"]: number,
	["maxexp"]: number,
	["upgrade"]: number,
	["level"]: number,
};
export type UserData = {
	["coins"]: number,
	["sharkcoins"]: number,
	["revivetokens"]: number,
	["slots"]: [{
		["shark"]: number,
		["dead"]: boolean,
		["hp"]: number,
		["maxhp"]: number,
		["hunger"]: number,
		["maxhunger"]: number,
		["exp"]: number,
		["maxexp"]: number,
		["upgrade"]: number,
		["level"]: number,
	}, {
		["shark"]: number,
		["dead"]: boolean,
		["hp"]: number,
		["maxhp"]: number,
		["hunger"]: number,
		["maxhunger"]: number,
		["exp"]: number,
		["maxexp"]: number,
		["upgrade"]: number,
		["level"]: number,
	}, {
		["shark"]: number,
		["dead"]: boolean,
		["hp"]: number,
		["maxhp"]: number,
		["hunger"]: number,
		["maxhunger"]: number,
		["exp"]: number,
		["maxexp"]: number,
		["upgrade"]: number,
		["level"]: number,
	}],
};

export declare const SpawnSlot: {
	fire: (value: number) => void;
};
export declare const SpawnResult: {
	on: (callback: (value: "Success" | "Fail") => void) => () => void;
};
export declare const PlayerDataEvent: {
	on: (callback: (value: {
		["coins"]: number,
		["sharkcoins"]: number,
		["revivetokens"]: number,
		["slots"]: [{
			["shark"]: number,
			["dead"]: boolean,
			["hp"]: number,
			["maxhp"]: number,
			["hunger"]: number,
			["maxhunger"]: number,
			["exp"]: number,
			["maxexp"]: number,
			["upgrade"]: number,
			["level"]: number,
		}, {
			["shark"]: number,
			["dead"]: boolean,
			["hp"]: number,
			["maxhp"]: number,
			["hunger"]: number,
			["maxhunger"]: number,
			["exp"]: number,
			["maxexp"]: number,
			["upgrade"]: number,
			["level"]: number,
		}, {
			["shark"]: number,
			["dead"]: boolean,
			["hp"]: number,
			["maxhp"]: number,
			["hunger"]: number,
			["maxhunger"]: number,
			["exp"]: number,
			["maxexp"]: number,
			["upgrade"]: number,
			["level"]: number,
		}],
	}) => void) => () => void;
};
export declare const IngameDataEvent: {
	on: (callback: (value: {
		["shark"]: number,
		["dead"]: boolean,
		["hp"]: number,
		["maxhp"]: number,
		["hunger"]: number,
		["maxhunger"]: number,
		["exp"]: number,
		["maxexp"]: number,
		["upgrade"]: number,
		["level"]: number,
	}) => void) => () => void;
};
