// Types generated by Zap v0.6.29 (https://github.com/red-blox/zap)
export type UserData = {
	["coins"]: number,
	["gems"]: number,
	["revivetokens"]: number,
	["slots"]: [{
		["shark"]: number,
		["dead"]: boolean,
		["hunger"]: number,
		["exp"]: number,
		["level"]: number,
	}, {
		["shark"]: number,
		["dead"]: boolean,
		["hunger"]: number,
		["exp"]: number,
		["level"]: number,
	}, {
		["shark"]: number,
		["dead"]: boolean,
		["hunger"]: number,
		["exp"]: number,
		["level"]: number,
	}],
};
export type SharkSlot = {
	["shark"]: number,
	["dead"]: boolean,
	["hunger"]: number,
	["exp"]: number,
	["level"]: number,
};
export type PartialSharkSlot = {
	["shark"]?: number | undefined,
	["dead"]?: boolean | undefined,
	["hunger"]?: number | undefined,
	["exp"]?: number | undefined,
	["level"]?: number | undefined,
};
